### ISSUE TITLE
[Feature request]: Keep buttons away from the overflow menu in old layout UI

### ISSUE THREAD

**Issue by sliceanddice9** [sapondanaisriwan/AdashimaaTube#115]
### Describe the change you'd like

If some or all of the - **_Share, Clip, Save, Download_** and **_Thanks_** buttons are enabled/not hidden via AdashimaaTube, have those buttons kept visible on screen at all times rather than some of the buttons being demoted to the 3 dot overflow menu.

This might not work with the new layout UI due to lack of space but with the old layout UI there is plenty of room for the buttons to be placed on screen underneath the video player itself. 

That might mean the like/dislike icon statistics would have to be shifted slightly more to the left but this could easily be accommodated to make the buttons fit. 

What the old layout UI looks like now - 

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/59092472/a5d072ff-2440-4b3d-b749-2f1562e956d8)
 

My Feature Request for the old layout UI to look like - 

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/59092472/dcb71e08-fe02-4582-851a-7265a6ac692d)

**Comment by sapondanaisriwan** [comment]
Everything will work perfectly if Return YouTube Dislike fix the old description panel.

**Comment by sapondanaisriwan** [comment]
temporary fix
```css
ytd-watch-metadata #subscribe-button {
     display: none;
}
    
ytd-watch-metadata[flex-menu-enabled] #actions-inner.ytd-watch-metadata {
     width: 100% i;
}
```
