### ISSUE TITLE
Automatically collapse the "hamburger menu" on Subscriptions page

### ISSUE THREAD

**Issue by nick-s-b** [sapondanaisriwan/AdashimaaTube#117]
### Describe the change you'd like

Hi,
Depending on your screen resolution and window size, the hamburger menu on the left side will be either expanded or collapsed. More often than not, it's expanded on my computer. It's a useless waste of space to me and would prefer it collapsed at all times so I can see more thumbnails of the videos instead. Unfortunately, YT doesn't provide an option to keep it collapsed at all times.

![collapse](https://github.com/sapondanaisriwan/AdashimaaTube/assets/7957590/2c07f480-ffa1-4d78-9beb-14de89bfaef2)

Could someone please figure out how to keep it collapsed? Thank you so much for an AMAZING script!

**Comment by sapondanaisriwan** [comment]
Try this
```css

    #content.ytd-app {
        &:has(#page-manager > ytd-browse[page-subtype="subscriptions"]:not([hidden])) {
            & > tp-yt-app-drawer {
                visibility: hidden !important;
                display: none !important;
            }

            & > ytd-mini-guide-renderer {
                visibility: visible !important;
                display: block !important;
            }
            &[guide-persistent-and-visible] ytd-page-manager.ytd-app {
                margin-left: var(--ytd-mini-guide-width) !important;
            }
        }
    }

    ytd-two-column-browse-results-renderer.grid:not(.grid-disabled) {
        width: 100% !important;
    }
```
