### ISSUE TITLE
[Bug]: overlapping elements

### ISSUE THREAD

**Issue by sapondanaisriwan** [sapondanaisriwan/AdashimaaTube#137]
### Describe the bug

temporary fix
```css
    ytd-watch-metadata {
        display: none !important;
    }

    #meta-contents[hidden],
    #info-contents[hidden] {
        display: block !important;
    }
```

### Screenshots

![image](https://github.com/sapondanaisriwan/AdashimaaTube/assets/64634605/c2fda2ef-108f-4fe8-b083-64d43835ab6e)

### What version of AdashimaaTube are you using?

v2.3.4
