### ISSUE TITLE
[Feature request]: Remove/Hide "Transcript" section at video page's description box after clicked 

### ISSUE THREAD

**Issue by MossyMosMos** [sapondanaisriwan/AdashimaaTube#174]

**Comment by ItsProfessional** [comment]
```css
ytd-video-description-transcript-section-renderer { display: none; }
```
